openapi: "3.0.0"
info:
  description: API Reference
  version: 1.0.0
  title: Python Flask RESTful API
servers:
  - url: http://localhost:5000
paths:
  /users:
    get:
      tags:
        - User
      summary: Find users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "204":
          description: Users not found
        "400":
          description: Invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: bad request
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: internal server error
  /users/{id}:
    get:
      tags:
        - User
      summary: Find user by ID
      parameters:
        - name: id
          in: path
          description: User id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Deed not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: internal server error
  /foods:
    get:
      tags:
        - Foods
      summary: Find food by name
      parameters:
        - name: name
          in: path
          description: string food name
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foods"
        "400":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: internal server error

components:
  schemas:
    User:
      type: object
      required:
        - username
        - firstName
        - lastName
        - email
      properties:
        _id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        subjects:
          type: string
    Foods:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        Killocalories:
          type: number
        Alpha-Carotene:
          type: number
        Beta-Carotene:
          type: number
        Carbohtdrate:
          type: number
        Cholesterol:
          type: number
        Choline:
          type: number
        Fiber:
          type: number
        Lycopene:
          type: number
        Manganese:
          type: number
        Protein:
          type: number
        Selenium:
          type: number
        Zinc:
          type: number
        Vitamon-B12:
          type: number
        Vitamin-B6:
          type: number
        Vitamin-C:
          type: number
        Vitamin-E:
          type: number
        Vitamin-K:
          type: number
